name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
      - name: create .env
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_SECRET_KEY: ${{ secrets.REACT_APP_SECRET_KEY }}
          directory: src
          file_name: .env
      - run: cd scr && ls -la
      - run: npm install && npm run build
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
